export default {
  SERTOES: {
    INHAMUS: "INHAMUS",
    CRATEUS: "CRATEUS",
  },
  TURISMO: {
    RELIGIOSO: "RELIGIOSO",
    AMBIENTAL: "AMBIENTAL",
    CULINARIO: "CULINARIO",
    HISTORICO: "HISTORICO",
  },
};
